version: '3.7'

services:
  redis:
    image: redis
    restart: always

  htmlhost:
    build:
      dockerfile: docker/Dockerfile
      context: .
    restart: always
    env_file: 
      - ./docker/.htmlhost.env
    ports:
      - "80:8000"
    depends_on:
      - redis
